### ISSUE TITLE
Press Release and FAQ's

### ISSUE THREAD

**Issue by INFINITYX00** [INFINITYX00/eslando#7]
Create a press release and FAQs for Eslando Digital Product Passports. 

We need clear + concise press release and faq's to inform the media, stakeholders, and potential users about the software's features, benefits, and value.

**Comment by hollrosey** [comment]
[FAQs and Press Release.pdf](https://github.com/INFINITYX00/eslando/files/15234512/FAQs.and.Press.Release.pdf)

**Comment by INFINITYX00** [comment]
FAQ's and press release done.
